version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - C:/Users/ruben/Desktop/PROYECTO_WORDPRESS/wordpress/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    environment:
      - DB_SERVER=db
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
