version: '3'
services:
  wordpress:
    image: wordpress:latest
    environment:
      DB_SERVER: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
    ports:
    - 8080:80
    volumes:
      - wordpress_data:/var/www/html
      - C:\Users\ruben\Documents\plugins\woocommerce:/var/www/html/wp-content/plugins/woocommerce
      - C:\Users\ruben\Documents\plugins\elementor:/var/www/html/wp-content/plugins/Elementor
      - C:\Users\ruben\Documents\plugins\elementor_pro:/var/www/html/wp-content/plugins/elementor_pro
      - C:\Users\ruben\Documents\plugins\woocommerce_payment:/var/www/html/wp-content/plugins/woocommerce_payment
      - C:\Users\ruben\Documents\plugins\yoast-seo:/var/www/html/wp-content/plugins/yoast-seo
      - C:\Users\ruben\Documents\plugins\litespeed-cache:/var/www/html/wp-content/plugins/litespeed-cache
      - C:\Users\ruben\Documents\themes\tienda_plantas:/var/www/html/wp-content/themes/tienda_plantas

    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
